### ISSUE TITLE
Support Jetty 10.0.0

### ISSUE THREAD

**Issue by rbygrave** [avaje/avaje-jex#9]

**Comment by tipsy** [comment]
Nice!

**Comment by rbygrave** [comment]
FYI @tipsy Jetty 11 support was this PR #10 - https://github.com/avaje/avaje-jex/pull/10/files

**Comment by tipsy** [comment]
We're already at 11 now? Purly a package name change, or?

**Comment by rbygrave** [comment]
Yes, 11 and 10 both came out today at the same time.  Yes, it seems to me that 11 was just about the package change to `jakarta.servlet` from `javax.servlet` (servlet api dependency provided by jetty etc).

**Comment by tipsy** [comment]
Got it! Will be interesting to see how it works. How is the project going in general?

**Comment by rbygrave** [comment]
> How is the project going in general?

Well "good" but ideally I wanted to get a web-sockets module done and I just haven't had the time yet. Other things have jumped ahead of it but it needs to be done to square away how the modules work for websockets support (with the optional dependencies).

I have made Jex "java module aware" with a module-info and it requires java 11. I know there is a lot of "non-belief" around the use of java modules but I like the more strict requirements it brings especially on libraries and Jetty 10 and 11 are both java module aware so I really ought to sort out the websockets functionality. As soon as I get that sorted I'll let you know.

Cheers, Rob.

**Comment by tipsy** [comment]
I guess it's objetively better to use the module system than not (for a library), but it is a bit of work. Thanks for the update!
