### ISSUE TITLE
Add a way to send a 204 no body?

### ISSUE THREAD

**Issue by rbygrave** [avaje/avaje-jex#90]
I don't think we have a nice/good way to send a 204 response without a body via Context interface?

It would be `context.write(new byte[0])` ... write an empty byte array. Do we need a better option like `content.sendEmpty(204)`?  With Nima/Helidon its `res.status(NO_CONTENT_204).send();`

**Comment by SentryMan** [comment]
handled by https://github.com/avaje/avaje-jex/pull/78, if you failed to write any response a 204 is sent automatically.

**Comment by rbygrave** [comment]
Hmm ok. Will go with that. Pondering if I like the explicit approach like helidon ... will ponder that some more.

**Comment by SentryMan** [comment]
I mean anything we add will be nothing but a placebo

**Comment by rbygrave** [comment]
Yeah, just pondering that sometimes its nice when things are explicit ... in the avaje-http generated code for Nima ... when a controller method returns null we explicitly generate code to send a 204 no body response - part of me like that in that its nice and explicit.
